TKY:
  num_nodes: 1843
  in_steps: 6
  out_steps: 6

  train_size: 0.6
  val_size: 0.2

  lr: 0.001
  weight_decay: 0.001
  milestones: [25, 45, 65]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300
  early_stop: 30
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 1843
    in_steps: 6
    out_steps: 6
    steps_per_day: 144
    input_dim: 1
    output_dim: 1
    input_embedding_dim: 32
    tod_embedding_dim: 24
    dow_embedding_dim: 8
    acc_embedding_dim: 8
    reg_embedding_dim: 8
    adaptive_embedding_dim: 24
    num_heads: 2
    num_layers: 3
    dropout: 0.1
    adp_dropout: 0.2
    dow_dropout: 0.1
    tod_dropout: 0