METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0003
  milestones: [20,30]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 200
  early_stop: 30
  use_cl: False
  cl_step_size: 2500
  #clip_grad: 5

  model_args:
    num_nodes: 207
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    
    adaptive_embedding_dim: 24
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 4
    dropout: 0.1

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0001
  milestones: [10, 30]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300
  early_stop: 20
  use_cl: False

  model_args:
    num_nodes: 325
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    
    adaptive_embedding_dim: 80
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3
    dropout: 0.1

PEMS03:
  num_nodes: 358
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True
  
  lr: 0.001
  weight_decay: 0.002
  milestones: [25, 45, 65]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300
  early_stop: 30
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 358
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 2
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 0
    dow_embedding_dim: 0
    adaptive_embedding_dim: 24
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 4
    dropout: 0.1


PEMS04:
  num_nodes: 307
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.002
  milestones: [25, 45, 65]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300
  early_stop: 30
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 307
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    
    adaptive_embedding_dim: 24
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 8
    dropout: 0.1

PEMS07:
  num_nodes: 883
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.002
  milestones: [25, 45, 65]
  lr_decay_rate: 0.1
  batch_size: 8
  max_epochs: 300
  early_stop: 30
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 883
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    
    adaptive_embedding_dim: 24
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 8
    dropout: 0.1

PEMS08:
  num_nodes: 170
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.002
  milestones: [25, 45, 65]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300
  early_stop: 30
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 170
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    adaptive_embedding_dim: 24
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 8
    dropout: 0.1
    support_len: 1
    
TKY:
  num_nodes: 1843
  in_steps: 6
  out_steps: 6

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.002
  milestones: [25, 45, 65]
  lr_decay_rate: 0.1
  batch_size: 8
  max_epochs: 300
  early_stop: 30
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 1843
    in_steps: 6
    out_steps: 6
    steps_per_day: 144
    input_dim: 2
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 0
    dow_embedding_dim: 0
    adaptive_embedding_dim: 24
    feed_forward_dim: 512
    num_heads: 4
    num_layers: 4
    dropout: 0.1
    fast: False
    support_len: 0

SD:
  num_nodes: 716
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.001
  milestones: [25, 45, 65]
  lr_decay_rate: 0.1
  batch_size: 8
  max_epochs: 300
  early_stop: 30
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 716
    in_steps: 12
    out_steps: 12
    steps_per_day: 96
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 0
    dow_embedding_dim: 0
    adaptive_embedding_dim: 24
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 6
    dropout: 0.1
    adp_dropout: 0.1
    fast: false


BA:
  num_nodes: 2352
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.001
  milestones: [25, 45, 65]
  lr_decay_rate: 0.1
  batch_size: 4
  max_epochs: 300
  early_stop: 30
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 2352
    in_steps: 12
    out_steps: 12
    steps_per_day: 96
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 0
    dow_embedding_dim: 0
    adaptive_embedding_dim: 24
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 2
    dropout: 0.1
    adp_dropout: 0.0
    fast: False
